### ISSUE TITLE
gossip: failure causes disconnect

### ISSUE THREAD

**Issue by bmancini55** [altangent/node-lightning#140]
This is caused failures propagated in #139, but highlights a potentially bigger issue. Need to investigate why the state machine failure is causing a disconnect:

```
2020-09-16T13:58:35.042Z [INF] app: msg: 2, type: 264 ReplyChannelRangeMessage 
2020-09-16T13:58:35.042Z [DBG] gossip 03d37fca0656558d: received reply_channel_range - full_info=0 start_block=569556 end_block=607565 scid_count=8000
2020-09-16T13:58:35.058Z [ERR] app: Error: reply_channel_range had no information
    at ChannelRangeQuery._handleReply (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:233:27)
    at ChannelRangeQuery._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:190:22)
    at GossipPeer.emit (events.js:327:22)
    at GossipPeer.EventEmitter.emit (domain.js:483:12)
    at GossipPeer._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/GossipPeer.ts:142:18)
    at Peer.emit (events.js:315:20)
    at Peer.EventEmitter.emit (domain.js:483:12)
    at Peer._processMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:404:18)
    at Peer._onSocketData (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:287:22)
    at NoiseSocket.emit (events.js:315:20)
2020-09-16T13:58:35.063Z [INF] app: msg: 3, type: 264 ReplyChannelRangeMessage 
2020-09-16T13:58:35.063Z [DBG] gossip 03d37fca0656558d: received reply_channel_range - full_info=0 start_block=607565 end_block=632369 scid_count=8000
2020-09-16T13:58:35.064Z [ERR] app: Error: reply_channel_range had no information
    at ChannelRangeQuery._handleReply (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:233:27)
    at ChannelRangeQuery._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:190:22)
    at GossipPeer.emit (events.js:327:22)
    at GossipPeer.EventEmitter.emit (domain.js:483:12)
    at GossipPeer._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/GossipPeer.ts:142:18)
    at Peer.emit (events.js:315:20)
    at Peer.EventEmitter.emit (domain.js:483:12)
    at Peer._processMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:404:18)
    at Peer._onSocketData (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:287:22)
    at NoiseSocket.emit (events.js:315:20)
2020-09-16T13:58:35.069Z [INF] app: msg: 4, type: 264 ReplyChannelRangeMessage 
2020-09-16T13:58:35.070Z [DBG] gossip 03d37fca0656558d: received reply_channel_range - full_info=0 start_block=632369 end_block=647538 scid_count=8000
2020-09-16T13:58:35.070Z [ERR] app: Error: reply_channel_range had no information
    at ChannelRangeQuery._handleReply (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:233:27)
    at ChannelRangeQuery._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/ChannelRangeQuery.ts:190:22)
    at GossipPeer.emit (events.js:327:22)
    at GossipPeer.EventEmitter.emit (domain.js:483:12)
    at GossipPeer._onMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/gossip/GossipPeer.ts:142:18)
    at Peer.emit (events.js:315:20)
    at Peer.EventEmitter.emit (domain.js:483:12)
    at Peer._processMessage (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:404:18)
    at Peer._onSocketData (/home/bmancini/code/altangent/node-lightning/packages/wire/lib/Peer.ts:287:22)
    at NoiseSocket.emit (events.js:315:20)
2020-09-16T13:58:35.071Z [INF] app: msg: 5, type: 264 ReplyChannelRangeMessage 
2020-09-16T13:58:35.071Z [DBG] gossip 03d37fca0656558d: received reply_channel_range - full_info=1 start_block=647538 end_block=4294967294 scid_count=862
2020-09-16T13:58:35.071Z [DBG] gossip 03d37fca0656558d: received final reply_channel_range height 4294967295 >= query_channel_range height 4294967295
2020-09-16T13:58:35.088Z [DBG] peer 03d37fca0656558d: socket closed
2020-09-16T13:58:35.088Z [DBG] peer 03d37fca0656558d: reconnecting in 15.0s
```

**Comment by bmancini55** [comment]
Ooook.  So this is the result of `ChannelRangeQuery` promise result working for only a single error: 
https://github.com/altangent/node-lightning/blob/d89a1c2d3f8aab72f258afc4d550c36e4e8a3f7f/packages/wire/lib/gossip/ChannelRangeQuery.ts#L127

If we receive multiple bad messages we may trigger multiple failures.  The event emitter will emit these... then it will bubble up to the error handling in Peer and and close the connection:
https://github.com/altangent/node-lightning/blob/d89a1c2d3f8aab72f258afc4d550c36e4e8a3f7f/packages/wire/lib/Peer.ts#L289
